---
- name: myFAIR with gunicorn
  lineinfile:
    dest: '{{ myFAIR_install_path }}/myFAIR/settings.py'
    regexp: "'DIRS':"
    line: "        'DIRS': ['./myFAIR', 'html'],"

- name: Install gunicorn in myFAIR virtualenv
  pip:
    name: gunicorn
    virtualenv: '{{ myFAIR_venv_path }}'

- name: Install gunicorn service
  template:
    src: gunicorn.service.j2
    dest: '/etc/systemd/system/myfair.service'
  become_user: root
  become_method: sudo

- name: Start myFAIR
  service:
    name: myfair
    state: started
    enabled: yes
  become_user: root
  become_method: sudo
