---
- name: Install prerequisites
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python3
    - python3-pip
    - python3-venv
    - lftp

- name: Create myFAIR directory
  file:
    path: '{{ myFAIR_install_path }}'
    state: directory
